### ISSUE TITLE
Book review and interview

### ISSUE THREAD

**Issue by brucou** [rtfeldman/elm-in-action#11]
Hi Richard (@rtfeldman),

I am a news editor for [InfoQ](https://www.infoq.com/). Would you be interested in a book review for *Elm in Action* and a short interview (Q&A) on it? 

You may not necessarily know InfoQ so let me tell a few quick things about it. [InfoQ's mission](https://www.infoq.com/about-infoq/) is to help dev teams adopt new technologies and practices. InfoQ's particularity is that content is written by software engineers/professional developers over professional writers. Our primary audience are tech leads, senior developers and software architects. 

We regularly do book reviews (see [here](https://www.infoq.com/book-review/)) on a variety of subjects but we have never covered Elm so I am excited to learn about the new *Elm in Action*. It would be great if you would find the time to do this. I plan to increase our [Elm coverage](https://www.infoq.com/elmlang/) this year and I believe this fits right with the interests of our readers, ears of which Elm may not so easily reach.

Let me know if that is of any interest to you. I hope this finds you well and safe in these troubled days.
Kind regards

**Comment by rtfeldman** [comment]
Sure! What's an email address where I can contact you?

**Comment by brucou** [comment]
Great! @rtfeldman olivier.couriol@gmail.com. Can you please delete this message once you wrote down my email? Trying to avoid getting a ton of extra spam.

**Comment by rtfeldman** [comment]
Got it, thanks! Comment deleted as requested, and I'll follow up with you via email. 😄
