### ISSUE TITLE
elm.js at top level causes problems with VSCode on Windows

### ISSUE THREAD

**Issue by melston** [rtfeldman/elm-in-action#9]
When using VSCode with the elm tooling extension on Windows the presence of the elm.js file at the top level of the project causes a popup every time you open one of the elm files in the src directory.  It complains that "'console' is undefined".

The recommendation (taken from [an elm-tooling issue](https://github.com/elm-tooling/elm-language-client-vscode/issues/82) ) is to not name the bundle 'elm.js'.

**Comment by rtfeldman** [comment]
Thanks! This has already been fixed in the final draft of the book (it uses `app.js` throughout now) but I haven't circled back and updated this repo yet. :smile:

**Comment by melston** [comment]
In the meantime I took a slightly different approach (which seems to work).  I use 'elm.js' but put it in a 'js' subdirectory.  VSCode is fine with that and I don't see any other issues.  I did update the index.html file accordingly.

**Comment by razzeee** [comment]
To add some more info, it's not due to VSCode, but how your shell handles file endings in windows.
